### ISSUE TITLE
Next release inquiry

### ISSUE THREAD

**Issue by davidcao1337** [nodevault/node-vault#230]
Hello, I was wondering when the next version of node vault is planned to release? I'm interested in the [TLS cert based authentication](https://github.com/nodevault/node-vault/blob/master/features.md#vaultcertlogin) that's seen in the repo, but isn't in the 0.9.22 release.

Thanks.

**Comment by vetlevo** [comment]
> Hello, I was wondering when the next version of node vault is planned to release? I'm interested in the [TLS cert based authentication](https://github.com/nodevault/node-vault/blob/master/features.md#vaultcertlogin) that's seen in the repo, but isn't in the 0.9.22 release.
> 
> Thanks.

The new maintainer(s) of the package has not been granted the token yet that is required to update the packages in the NPM registry, see this [issue](https://github.com/nodevault/node-vault/issues/150) for more info. It would be great if someone was able to reach the owner of the GitHub repo & NPM repo @kr1sp1n so that we could sort this out ...

**Comment by aviadhahami** [comment]
Hi @vetlevo and @davidcao1337 - please use v.0.10.0 as it is now released :D 

Closing as of now ^_^
